# Generated by Django 5.1.3 on 2025-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='store_otp_expires_8265f1_idx'),
        ),
    ]
