# Generated by Django 5.1.3 on 2025-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['value']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'value')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pc', 'Pieces'), ('dz', 'Dozen'), ('box', 'Box'), ('pack', 'Pack')], default='pc', max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='updated_at',
        ),
    ]
