# Generated by Django 5.1.3 on 2025-03-11 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['value', 'packaging', 'color', 'size']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('BLU', 'Blue'), ('GRN', 'Green'), ('YLW', 'Yellow'), ('BLK', 'Black'), ('WHT', 'White'), ('BRN', 'Brown'), ('MLT', 'Multicolor')], help_text='Color variant if applicable', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='packaging',
            field=models.CharField(choices=[('PKT', 'Packet'), ('BTL', 'Bottle'), ('BOX', 'Box'), ('JAR', 'Jar'), ('BAG', 'Bag'), ('TIN', 'Tin')], default='PKT', help_text='Type of packaging', max_length=3),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('FS', 'Free Size')], help_text='Size variant if applicable', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pc', 'Pieces'), ('dz', 'Dozen'), ('box', 'Box'), ('pack', 'Pack')], default='pc', help_text='Unit of measurement', max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Numeric value (e.g., 1 for 1kg, 0.5 for 500ml)', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'value', 'packaging', 'color', 'size')},
        ),
    ]
