# Generated by Django 5.1.3 on 2025-04-07 12:54

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem_order_store_order_user_id_c9744e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.ngo_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_image_path),
        ),
    ]
