# Generated by Django 5.1.3 on 2025-03-13 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productvariant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ngo',
            options={'ordering': ['shg_name'], 'verbose_name': 'NGO', 'verbose_name_plural': 'NGOs'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'value', 'packaging', 'color', 'size']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, help_text='Location name must be unique', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='shg_name',
            field=models.CharField(db_index=True, help_text='Self Help Group name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active'], name='store_cart_user_id_93c944_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at'], name='store_cart_created_bb94c8_idx'),
        ),
        migrations.AddIndex(
            model_name='ngo',
            index=models.Index(fields=['location', 'shg_name'], name='store_ngo_locatio_178058_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='store_produ_categor_2f0f44_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='store_produ_sku_027c55_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='store_produ_is_acti_4a2e98_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'value', 'unit', 'packaging', 'color', 'size'), name='unique_product_variant'),
        ),
    ]
