# Generated by Django 5.1.3 on 2025-03-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_location_options_alter_ngo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Minimum stock level before notification'),
        ),
    ]
