# Generated by Django 5.1.3 on 2025-03-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_stock_threshold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductThumbnail',
        ),
    ]
