# Generated by Django 5.1.3 on 2025-04-09 07:57

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_useractivity_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='image',
            field=models.ImageField(blank=True, help_text='Image will be stored in store/static/media/ngos/<ngo_id>/', null=True, upload_to=store.models.ngo_image_path),
        ),
    ]
