# Generated by Django 5.1.3 on 2025-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ngo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_unit',
            field=models.CharField(choices=[('pc', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('m', 'Meters'), ('cm', 'Centimeters'), ('sqm', 'Square Meters'), ('pack', 'Pack'), ('box', 'Box')], default='pc', help_text='Standard unit of measurement for this product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Value in standard units (e.g., 500 for 500g)', max_digits=10),
        ),
    ]
