# Generated by Django 5.1.3 on 2025-03-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_create_user_profiles'),
        ('store', '0008_userprofile_is_verified'),
    ]

    operations = [
    ]
