# Generated by Django 5.1.3 on 2025-03-19 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['value']},
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_variant',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='store_produ_sku_027c55_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='store_produ_is_acti_4a2e98_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'value', 'unit')},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pc', 'Pieces')], default='pc', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='varianttype',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pc', 'Pieces')], default='pc', max_length=10),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
    ]
